name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Koyeb
        env:
            KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          curl -X POST https://api.koyeb.com/v1/apps/invoicecalculations/deployments \
          -H "Authorization: Bearer $KOYEB_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"image": "invoicecalculations:latest"}'
