name: Deployment Update

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            
            - name: Create deployment
              env:
                DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
              run: |
                curl -X POST \
                    -H "Authorization: token $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/deployments \
                    -d "{\"ref\":\"${{ github.ref_name }}\",\"environment\":\"production\",\"description\":\"Deployed to production\",\"auto_merge\":false,\"required_contexts\":[],\"payload\":{\"url\":\"https://high-bertina-tmchuynh-6e70f129.koyeb.app/\"}}"